apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazon
  labels:
    app: amazon
spec:
  replicas: 3
  selector:
    matchLabels:
      app: amazon
  template:
    metadata:
      labels:
        app: amazon
    spec:
     containers:
     - name: amazon
       image: update image
       ports:
       - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: amazon-service
spec:
  type: LoadBalancer
  selector:
    app: amazon
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000  
